name: Esegui Bot Calcio
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v2
      - name: Configura Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installa librerie
        run: pip install requests
      - name: Avvia il Bot
        run: python bot.py
